verison: '3'

services:

  blog_backend:
    build:
      context: ./blog_backend/
      dockerfile: Dockerfile
#    ports:
#      -8001:8001
    depends_on:
      - mysql
    environment:
      BLOG_BACKEND_DB_HOST: mysql
      BLOG_BACKEND_DB_PASSWORD: mysql
    networks:
      - my-bridge

  blog_fronted:
    build:
      context: ./blog_frontend/
      dockerfile: Dockerfile
#    ports:
#    - 8002:8002
    networks:
      - my-bridge

  mysql:
    image: mysql:8.0.21
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: blog_backend
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - my-bridge

volumes:
  mysql-data:

networks:
  my-bridge:
    driver: bridge