version: "3.3"

services:
  blog_backend:
    build: ./blog_backend/.
    volumes:
      - ./blog_backend:/enlighten
    ports:
      - "8000:8000"
    links:
      - mysql
    networks:
      - front-tier
      - back-tier

  blog_frontend:
    build: ./blog_frontend/.
    volumes:
      - ./blog_frontend:/enlighten
    ports:
      - "8001:8001"
    links:
      - mysql
    networks:
      - front-tier
      - back-tier
  mysql:
    image: mysql:8.0.21
    volumes:
      - "db-data:/var/lib/mysql/data"
    networks:
      - back-tier

volumes:
  db-data:

networks:
  front-tier:
  back-tier:
