# Generated by Django 2.1.10 on 2020-09-03 08:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verifycode',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 3, 16, 51, 41, 415942), verbose_name='添加时间'),
        ),
    ]
