# Generated by Django 3.0.1 on 2021-03-25 02:54

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('article_id', models.CharField(max_length=100, verbose_name='文章id')),
                ('article_name', models.CharField(max_length=100, verbose_name='文章标题')),
                ('summary', models.CharField(blank=True, max_length=200, null=True, verbose_name='文章摘要')),
                ('category', models.CharField(default='python', max_length=100, verbose_name='所属类别')),
                ('author', models.CharField(max_length=50, verbose_name='作者')),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, null=True, size=None, verbose_name='标签')),
                ('content', models.TextField(blank=True, null=True, verbose_name='文章详情内容')),
                ('publish_time', models.CharField(max_length=50, null=True, verbose_name='发布时间')),
                ('image_url', models.TextField(max_length=500, null=True, verbose_name='图片链接')),
                ('star_count', models.IntegerField(default=0, null=True, verbose_name='点赞数')),
                ('comment_count', models.IntegerField(default=0, null=True, verbose_name='评论数')),
                ('comment', models.CharField(max_length=500, null=True, verbose_name='评论')),
            ],
            options={
                'verbose_name': '文章详情',
                'verbose_name_plural': '文章详情',
                'db_table': 'article_detail',
            },
        ),
        migrations.CreateModel(
            name='ArticleList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('article_id', models.CharField(max_length=100, verbose_name='文章id')),
                ('article_name', models.CharField(max_length=100, verbose_name='文章标题')),
                ('summary', models.CharField(max_length=200, null=True, verbose_name='文章摘要')),
                ('category', models.CharField(default='python', max_length=100, verbose_name='所属类别')),
                ('author', models.CharField(max_length=50, verbose_name='作者')),
                ('image', models.TextField(max_length=500, null=True, verbose_name='文章图片')),
                ('origin', models.CharField(max_length=100, null=True, verbose_name='爬取于')),
                ('content', models.TextField(blank=True, null=True, verbose_name='文章详情内容')),
                ('scraped_date_time', models.DateTimeField(auto_now=True, verbose_name='爬取时间')),
                ('publish_time', models.CharField(max_length=50, null=True, verbose_name='发布时间')),
                ('star_count', models.IntegerField(default=0, null=True, verbose_name='点赞数')),
                ('comment_count', models.IntegerField(default=0, null=True, verbose_name='评论数')),
            ],
            options={
                'verbose_name': '文章列表',
                'verbose_name_plural': '文章列表',
                'db_table': 'article_list',
                'ordering': ['-publish_time'],
            },
        ),
        migrations.CreateModel(
            name='ArticleMetadata',
            fields=[
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('meta_id', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='文章元数据id')),
                ('meta_name', models.CharField(max_length=100, verbose_name='文章元数据name')),
                ('content', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), size=None, verbose_name='存储的内容列表')),
            ],
            options={
                'verbose_name': '文章元数据',
                'verbose_name_plural': '文章元数据',
                'db_table': 'article_metadata',
            },
        ),
    ]
