# Generated by Django 2.1.10 on 2020-09-03 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articledetail',
            name='id',
        ),
        migrations.AlterField(
            model_name='articledetail',
            name='article_id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='文章id'),
        ),
    ]
